package org.ancestra.evolutive.enums;

/**
 * A but de rep�rage.
 */

public enum Im {
	Im00("%1"),
	Im01("Tu as récupéré <b>%1</b> points de vie."),
	Im02("Tu as appris le métier <b>%1</b>."),
	Im03("Tu as appris le sort <b>%1</b>."),
	Im04("Ton humeur guerrière reprend le dessus. Tu peux être défié..."),
	Im05("Tu es maintenant tranquille. On ne peut plus te défier..."),
	Im06("Position sauvegardée."),
	Im07("Tu as récupéré <b>%1</b> points d'énergie."),
	Im08("Tu as gagné <b>%1</b> points d'expérience."),
	Im09("Tu as gagné <b>%1</b> points de sagesse."),
	Im010("Tu as gagné <b>%1</b> points de force."),
	Im011("Tu as gagné <b>%1</b> points de chance."),
	Im012("Tu as gagné <b>%1</b> points d'agilité."),
	Im013("Tu as gagné <b>%1</b> points de vitalité."),
	Im014("Tu as gagné <b>%1</b> points d' intelligence."),
	Im015("Tu as gagné <b>%1</b> points de caractéristique."),
	Im016("Tu as gagné <b>%1</b> points de sort."),
	Im017("Tu as gagné <b>%1</b> XP dans le métier <b>%2</b>."),
	Im018("%1 vous a mis à la porte de sa maison..."),
	Im019("%1 avait d'autres clients et a dû vous laisser."),
	Im020("Tu as dû donner %1 kamas pour pouvoir accéder à ce coffre."),
	Im021("Tu as obtenu %1 '%2'."),
	Im022("Tu as perdu %1 '%2'."),
	Im023("Tu viens de récupérer %1 points de stats."),
	Im024("Tu viens de mémoriser un nouveau zaap."),
	Im025("Votre familier vous fait la fête!"),
	Im026("Vous donnez à manger à votre familier alors qu'il n'avait plus faim. Il se force pour vous faire plaisir"),
	Im027("Vous donnez à manger à répétition à votre familier déjà obèse. Il avale quand même la ressource et fait une indigestion."),
	Im028("Vous donnez à manger à votre familier tout famélique. Il dévore tout le plus rapidement possible et son estomac en souffre. Mais il reprend du poids."),
	Im029("Vous donnez à manger à votre familier. Il semble qu'il avait très faim."),
	Im030("Vous donnez à manger à votre gros familier qui se précipite dessus tellement il semble avoir faim. Il mange trop rapidement et se fait mal. Au moins il a maigri un peu"),
	Im031("Vous donnez à manger à votre familier famélique qui traînait comme un zombi. Il se force à manger mais la nourriture qu'il avale fait 3 fois son estomac et il se tord de douleur. Au moins il a mangé."),
	Im032("Votre familier apprécie le repas."),
	Im033("Tu viens de ressusciter, mais ton énergie est encore faible. Prends garde ou les esprits te rattraperont."),
	Im034("Tu as perdu <b>%1</b> points d'énergie."),
	Im036("%1 vient de rejoindre le combat en spectateur."),
	Im037("Vous êtes désormais considéré comme absent."),
	Im038("Vous n'êtes plus considéré comme absent."),
	Im039("Le mode 'spectateur' est activé."),
	Im040("Le mode 'spectateur' est désactivé."),
	Im041("La %1 menant à votre coeur de ville du %2 est attaquée."),
	Im042("La milice a envoyé du renfort pour aider l'équipe de %1 à se défendre."),
	Im043("Ton alignement vient d'augmenter de %1 et est désormais de %2."),
	Im044("Ton alignement est désormais de %1."),
	Im045("Tu as gagné %1 kamas."),
	Im046("Tu as perdu %1 kamas."),
	Im047("Ton mariage avec %1 a été annulé."),
	Im048("Le mariage entre %1 et %2 a été annulé."),
	Im049("En voyant cette porte ainsi illuminée, votre larve dorée s'est précipité pour la franchir, vous n'avez pas pu la suivre. Nul doute qu'elle rejoindra les autres larves maintenant. Une perle dorée gît là où la larve se trouvait quelques secondes auparavent."),
	Im050("Vous êtes maintenant en mode invisible."),
	Im051("Vous n'êtes plus en mode invisible."),
	Im052("<b>%1</b> suit votre déplacement."),
	Im053("<b>%1</b> ne suit plus votre déplacement."),
	Im054("Nouvelle quête : <b>%1</b>"),
	Im055("Quête mise à jour : <b>%1</b>"),
	Im056("Quête terminée : <b>%1</b>"),
	Im057("Vous ne disposez pas d'assez de kamas pour acquiter la taxe de mise en vente..."),
	Im058("Vous ne pouvez pas mettre plus d'objets en vente actuellement..."),
	Im059("Vous ne pouvez pas mettre plus d'objets en vente actuellement..."),
	Im060("Cet objet ne peut être accepté ici vu sa rareté..."),
	Im061("Cet objet ne fait pas partie des catégories prévues dans cet hôtel de vente."),
	Im062("Action annulée pour cause de surcharge..."),
	Im063("Vous ne disposez pas d'assez de kamas pour acheter cet objet."),
	Im064("Cet objet n'est plus disponible à ce prix. Quelqu'un a été plus rapide..."),
	Im065("Votre compte en banque a été crédité de %1 kamas suite à la vente de '%3'."),
	Im066("Votre objet bon marché a été acheté immédiatement par les miliciens qui en feront, bien entendu, très bon usage. Votre compte en banque a été crédité de %1 kamas."),
	Im067("Un de vos objets n'a pas été vendu dans le temps limite. Vous le retrouverez à votre banque."),
	Im068("Lot acheté."),
	Im069("Les autres vous voient maintenant hors ligne..."),
	Im070("Les autres vous revoient en ligne à nouveau."),
	Im071("Les autres vous voient maintenant hors ligne, sauf vos amis."),
	Im072("Vous êtes actuellement absent, cette personne risque de ne pas pouvoir vous répondre..."),
	Im073("Votre compte en banque a été crédité de %1 kamas suite à la vente de %4 '%3' lorsque vous étiez hors jeu."),
	Im074("Tu as gagné <b>%1</b> points d' honneur."),
	Im075("Tu as gagné <b>%1</b> points de déshonneur."),
	Im076("Tu as perdu <b>%1</b> points d' honneur."),
	Im077("Tu as perdu <b>%1</b> points de déshonneur."),
	Im078("Vous avez dû lâcher votre arme à deux mains pour équiper un bouclier."),
	Im079("Vous avez dû lâcher votre bouclier pour équiper une arme à deux mains."),
	Im080("Vous gagnez %1 points d'honneur en récompense de votre bravoure."),
	Im081("Vous perdez %1 points d'honneur suite à cette défaite."),
	Im082("Votre bravoure vous a fait grimper au rang %1."),
	Im083("Vous avez été dégradé au rang %1."),
	Im084("Vous êtes sanctionné par %1 point(s), de déshonneur pour ce combat déshonorant"),
	Im085("Vous rachetez votre déshonneur de %1 point(s), avec cet acte de bravoure."),
	Im086("Vous devez repousser l'attaque sur la zone %1 avant que nos ennemis ne s'en emparent."),
	Im087("Le coeur de la zone %1 est ouvert aux ennemis, protégez le !"),
	Im088("Le coeur de la zone %1 est refermé... Terrassez les ennemis encore présents et la victoire est acquise."),
	Im089("Vos alliés attaquent en ce moment la zone %1. Ils ont certainement besoin de votre aide."),
	Im090("Le coeur de la zone %1 a été ouvert par vos alliés, vous pouvez tenter de capturer ce lieu !"),
	Im091("Vous avez été téléporté hors d'une zone alignée ennemie..."),
	Im092("Vous avez récupéré %1 points d'énergie en vous reposant."),
	Im093("L'équipe n'accepte désormais que les membres du groupe du personnage principal."),
	Im094("L'équipe accepte les membres de tous les groupes."),
	Im095("L'équipe n'accepte plus de personnages supplémentaires."),
	Im096("L'équipe accepte de nouveau des personnages supplémentaires."),
	Im097("Les spectateurs seront admis initialement dans vos prochains combats."),
	Im098("Les spectateurs seront refusés initialement dans vos prochains combats."),
	Im099("Vos prochains combats seront joignables uniquement par votre groupe."),
	Im0100("Vos prochains combats ne seront plus joignables uniquement par votre groupe."),
	Im0101("Personne ne sera autorisé à rejoindre vos prochains combats."),
	Im0102("Tout le monde sera autorisé à rejoindre vos prochains combats."),
	Im0103("Demande d'aide signalée..."),
	Im0104("Demande d'aide annulée..."),
	Im0105("Votre monture apprécie le repas."),
	Im0106("Pour utiliser le canal d'alignement vous devez développer vos ailes à 3 ou plus, ou encore avoir choisi une spécialisation par les quêtes d'alignement (niveau de quêtes à partir de 20),"),
	Im0107("Surveille ton langage, t'es pas un Bwork."),
	Im0108("Avertissement avant sanction."),
	Im0109("Le dieu Sram sème la confusion mentale dans l'esprit du joueur."),
	Im0110("Votre monture%1 a été reprise de l'enclos %2 par %3"),
	Im0111("Votre monture mâle sauvage%1 s'est enfui aussitôt après avoir fécondé une femelle (enclos en %2),."),
	Im0112("Votre monture sauvage femelle%1, aussitôt après avoir mis bas, s'est enfuie."),
	Im0113("Par respect pour les autres aventuriers, vous décidez après mûre réflexion de ne pas céder à la tentation de participer à la cacophonie d'ordinaire habituelle de ces lieux."),
	Im0114("Impossible d'afficher des objets dans ce canal."),
	Im0115("Ce canal est restreint pour améliorer sa lisibilité. Vous pourrez envoyer un nouveau message dans %1 secondes. Ceci ne vous autorise cependant pas pour autant à surcharger ce canal."),
	Im0116("<b>Avertissement</b> : %1"),
	Im0117("Malgré vos talents, la magie n'opère pas et vous sentez l'échec de la transformation, ainsi que la diminution de la puissance de l'objet."),
	Im0118("Vous n'arrivez pas à assembler correctement les ingrédients, et vous n'arrivez pas à concevoir quoi que ce soit d'utilisable cette fois."),
	Im0119("« Miroir, mon beau miroir ... » Le miroir ne semble pas disposé à répondre à vos préoccupations esthétiques."),
	Im0120("L'horloge indique %1h%2."),
	Im0121("Cette horloge ne semble pas fonctionner."),
	Im0122("Sont-ce les restes d'une beuverie ou des encres d'imprimerie ?"),
	Im0123("Vous créez : %1"),
	Im0124("Une pensée vous vient à l'esprit : « Quel beau portrait de ma grand tante Danielle ! ... »"),
	Im0125("« coco ? »"),
	Im0126("« Il est exactement %1h%2. Coco »"),
	Im0127("Cette horloge n'est pas à l'heure, elle indique %1h%2."),
	Im0128("« Vous a-t-on déjà dit que vous ressembliez à %1 ? » s'enquit le miroir."),
	Im0129("« Je détiens la force toute puissante! »"),
	Im0130("« Savez-vous planter les choux ... »"),
	Im0131("« Ci-gît Hector, niveau 197, tué par le cri d'un Tofu affamé. »"),
	Im0132("« Attention ! Peinture fraîche »"),
	Im0133("« PIOU PIOU »"),
	Im0134("Cet oiseau empaillé, rembourré à la fleur de chanvre, sent bon le bwork malade."),
	Im0135("Vous vous réchauffez au coin du poêle. Il fait bon dans la pièce."),
	Im0136("Le poêle est éteint."),
	Im0137("Cet oiseau n'a pas l'air en forme, il vaudrait mieux l'achever d'un bon coup d'épée ..."),
	Im0138("Le piou se jette sur vous et vous arrache les yeux ... \nAh non, c'est une illusion, quelqu'un vous en veut ..."),
	Im0139("Vous ne pouvez plus parler dans ce canal, seuls les débutants présents dans Incarnam le peuvent. Vous pouvez néanmoins leur répondre en message privé pour les aider."),
	Im0140("Un tofu peinturluré s'échappe du tableau et vous attaque."),
	Im0141("Le tofu collé à la toile par la peinture semble vouloir se détacher du tableau."),
	Im0142("Le tofu est maintenant bien fixé ! Marylork est un vrai artiste réaliste."),
	Im0143("%1 est en ligne."),
	Im0144("Votre inventaire est plein. Votre récolte est perdue..."),
	Im0145("Vous faites halte devant cette uvre de magnificence, et l'ayant admiré en votre cur, vous vous exclamez avec enthousiasme : « Voilà donc le héros d'endurance qui, des épreuves des dieux, a su triompher. Voici donc le visage de ce guerrier légendaire qui sous l'égide de Féca atteignit le pinacle du firmament ». Puis, pour pondérer votre envolée lyrique, vous ajoutez : « Rhô ke c bo, il r0xX ! »."),
	Im0146("Que je suis beau !"),
	Im0147("Après vérification de ses registres, un gardien d'étable vous annonce, qu'il a libéré la monture dénommée « %1 » que vous lui aviez confié. \nIl était, en effet, sans nouvelles de vous ou de son nouveau propriétaire dans les délais fixés lors de l'échange."),
	Im0148("Les ailes sanglantes de Sacrieur, la Déesse des Martyrs, s'ouvrent devant vos yeux ébahis.\nCette statue apparut lors de l'avènement de la Déesse, générée par les pensées réunies de milliers de fidèles."),
	Im0149("Cette armure ancienne semble cacher les restes d'un passage secret qui a dû s'écrouler il y a bien longtemps.\nPeut-être qu'avec une pelle, une pioche, et beaucoup de courage... Hm, après réflexion, en fait non."),
	Im0150("De la main de <b>%2</b>, <b>%1</b> dit : %3"),
	Im0151("Votre <b>%1</b> vous murmure : %2"),
	Im0152("Précédente connexion sur votre compte effectuée le %3/%2/%1 à %4:%5 via l'adresse IP %6"),
	Im0153("Votre adresse IP actuelle est %1."),
	Im0154("Tu as oublié un sort de niveau %1 et tu as regagné %2 points de sort."),
	Im0155("Votre présence dans ce territoire ne vous a pas procuré d'honneur cette fois, vous aviez déjà vaillamment défendu il y a peu. Le prochain combat sera sans doute plus valorisant !"),
	Im0156("La porte du tribunal est fermée à clef."),
	Im0157("Ce canal n'est accessible en diffusion aux abonnés qu'à partir du niveau %1."),
	Im0158("Votre dragodinde %1 a été mise dans votre enclos suite à la vente de la ferme dans laquelle elle se trouvait."),
	Im0159("Votre arme ne peut contenir autant de runes ! Toutes les runes vous ont été rendues."),
	Im0160("Sanctuaire Hotomani"),
	Im0161("Une force invisible vous empêche de passer"),
	Im0162("Plus que <b>%2</b> tour(s), avant la déconnexion de <b>%1</b>"),
	Im0163("<b>%1</b> a visé le mur."),
	Im0164("Vous vous regardez dans le miroir, vous êtes moche."),ERROR("Erreur : %1"),
	Im11("Certaines conditions ne sont pas satisfaites"),
	Im110("Ton inventaire est plein, impossible d'y ajouter d'autres objets."),
	Im1100("Vous n'appartenez pas à la bonne guilde pour profiter de cet enclos."),
	Im1101("Vous ne disposez pas des droits de guildes suffisants pour cette opération."),
	Im1102("Cellule cible invalide."),
	Im1103("Impossible d'acheter un enclos supplémentaire. Une guilde peut acquérir un enclos après son niveau 10, puis un supplémentaire par tranche de 10 niveaux. Il faut en outre que la guilde soit agée de plus de 2 mois."),
	Im1104("Monture désignée invalide."),
	Im1105("L'étable est pleine. Vous ne pouvez conserver que 100 montures maximum."),
	Im1106("Votre inventaire de monture doit être vide pour pouvoir la déséquiper."),
	Im1107("L'enclos est plein pour le moment."),
	Im1108("Cette monture n'est plus disponible. Elle a dû s'enfuir. Les certificats ne permettent de conserver une monture qu'un temps limité."),
	Im1109("Attention ! Bavasser comme un Porkass est mal vu des autres aventuriers."),
	Im111("Tu as déjà appris ce métier."),
	Im1110("A peine entrée dans l'étable, votre monture s'accroupit et commence à mettre bas. Après quelques instants, vous pouvez constater que tout s'est bien passé. Vous voilà responsable d'une nouvelle monture."),
	Im1111("A peine entrée dans l'étable, votre monture s'accroupit et commence à mettre bas. Après quelques instants, vous pouvez constater que tout s'est bien passé. Vous voilà responsable de %1 nouvelles montures."),
	Im1112("Votre monture semble souffrir, et commence à mettre bas sa progéniture. Hélas, vous avez trop tardé à venir l'accompagner dans son travail, et son petit ne survit pas."),
	Im1113("Impossible de monter sur votre monture, elle est épuisée... Nourrissez-la, ou laissez-la se reposer dans un enclos."),
	Im1114("Votre monture, épuisée, refuse de vous porter plus loin."),
	Im1115("Seuls les comptes abonnés peuvent profiter des montures."),
	Im1116("Impossible dans votre état actuel."),
	Im1117("Impossible d'être sur une monture à l'intérieur d'une maison."),
	Im1118("Impossible d'entrer dans une demeure en restant sur sa monture."),
	Im1119("Impossible d'acheter un enclos sans avoir de monture."),
	Im112("Tu es trop chargé. Jette quelques objets pour pouvoir bouger..."),
	Im1120("Impossible d'interagir avec votre percepteur sur la carte même où vous vous êtes connecté."),
	Im1121("Avertissement avant sanction."),
	Im1122("L'abus de points d'exclamations est dangereux pour la santé !!!"),
	Im1123("Le principe de précaution vous a rendu muet pour %1 seconde(s),."),
	Im1124("A force de trop parler, vous en avez perdu la voix. Vous devriez vous taire pendant les %1 prochaines secondes."),
	Im1125("Le gardien de l'enclos a perdu trace de votre monture. Il vous propose en échange une même monture, mais qui vient de naître. C'est toujours mieux que rien..."),
	Im1126("Tu n'as pas les droits nécessaires"),
	Im1127("Incarnam ne vous est plus accessible désormais, votre expérience fait de vous un aventurier apte à parcourir le monde sans continuer dans cette zone..."),
	Im1128("Le montant de la transaction s'élève à %1 kamas. Malheureusement vous n'avez actuellement pas cette somme sur vous."),
	Im1129("Vous ne pouvez pas poser ceci au sol."),
	Im113("Cette action n'est pas autorisée sur cette carte."),
	Im1130("Vous ne pouvez pas atteindre cet endroit depuis votre position actuelle."),
	Im1131("Il faut être abonné"),
	Im1132("Il est interdit d'attaquer ceci pendant encore %1 minute(s),."),
	Im1133("Il est trop tôt"),
	Im1134("Ce n'est pas le bon moment"),
	Im1135("Vous devez appartenir à une guilde pour profiter de cette possibilité."),
	Im1136("La téléportation vers cette maison de guilde n'a pas été autorisée par son propriétaire."),
	Im1137("Vous êtes à court de potion de foyer de guilde."),
	Im1138("Votre percepteur est de mauvaise humeur, pour pouvoir récolter son butin revenez plus tard (%1h),."),
	Im1139("Attention, la fenêtre d'échange se fermera automatiquement dans %1 minutes."),
	Im114("Le joueur %1 était absent et n'a donc pas reçu votre message."),
	Im1140("La destination est en territoire hostile."),
	Im1141("La téléportation vers cette zone n'est pas autorisée aux joueurs neutres."),
	Im1142("Les tombes sont interdites en donjon, vous avez été ramené à votre dernier point de sauvegarde."),
	Im1143("Vous ne pouvez plus accéder à ce prisme."),
	Im1144("Vous avez besoin de vos ailes pour voler jusqu'à un autre prisme."),
	Im1145("Il n'y a pas assez de place ici."),
	Im1146("Vous ne pouvez pas poser de prisme sur cette carte."),
	Im1147("Vous ne pouvez pas poser de prisme dans cette zone."),
	Im1148("Pour poser un prisme il vous faut au préalable parader ostensiblement avec vos jolies ailes, tel un paon, pendant une période de 5 minutes."),
	Im1149("Il y a déjà un prisme dans cette zone."),
	Im115("Pour des raisons de maintenances, le serveur va être redémarré dans %1."),
	Im1150("Vous ne pouvez pas dissimuler vos ailes en ce lieu."),
	Im1151("Impossible d'acheter une maison supplémentaire. Une guilde peut partager une maison après son niveau 10, puis une supplémentaire par tranche de 10 niveaux. Il faut en outre que la guilde soit agée de plus de 2 mois."),
	Im1152("Vous ne pouvez pas poser de prisme dans cette zone : vous ne possédez pas assez de territoires de base."),
	Im1153("Vous ne pouvez pas poser de prisme dans cette zone : il reste trop d'ennemis. Pourchassez les ennemis encore présents pour que la balance du territoire vous soit favorable."),
	Im1154("Vous ne pouvez pas attaquer ce prisme durant sa première heure de vie."),
	Im1155("Vous devez être au minimum niveau 10 et de grade 3 pour poser un prisme."),
	Im1156("Vous ne pouvez prendre la place que d'un joueur ayant un grade inférieur au vôtre. Les plus haut gradés sont prioritaires !"),
	Im1157("Vous ne pouvez pas attaquer ce prisme, vos territoires sont trop éloignés pour permettre une percée dans cette zone."),
	Im1158("Seuls les téméraires triomphant d'une quête précise sont bienvenus."),
	Im1159("Vous êtes à court de potion d'enclos de guilde."),
	Im116("%1 : %2"),
	Im1160("Vous ne pouvez pas attaquer ce prisme dans cette zone : trop d'ennemis sont présents. Pourchassez les ennemis encore présents ou attaquez dans une zone moins peuplée pour que la balance du territoire vous soit favorable."),
	Im1161("Vous ne pouvez pas équiper un objet vivant directement, essayez plutôt de l'associer sur un objet équipé qu'il affectionne."),
	Im1162("Vous ne pouvez pas associer un objet vivant à un objet inanimé non échangeable."),
	Im1163("Votre objet vivant n'a pas l'air de vouloir ingurgiter quoi que ce soit pour le moment."),
	Im1164("Une sauvegarde du serveur est en cours... Vous pouvez continuer de jouer, mais l'accès au serveur est temporairement bloqué. La connexion sera de nouveau possible d'ici quelques instants. Merci de votre patience."),
	Im1165("La sauvegarde du serveur est terminée. L'accès au serveur est de nouveau possible. Merci de votre compréhension."),
	Im1166("Votre personnage ne peut s'incarner tout de suite dans cet avatar, entre deux incarnations vous devez vous reposer au moins 15 minutes."),
	Im1167("Vous ne pouvez pas poser de percepteur ici avant %1 minutes"),
	Im1168("Vous ne pouvez pas poser plus de %1 percepteur(s), par zone."),
	Im1169("Impossible de lancer ce sort : vous ne le possédez pas !"),
	Im117("%1 vous a rendu muet pour %2 minute(s),."),
	Im1170("Impossible de lancer ce sort : Vous avez %1 PA disponible(s), et il vous en faut %2 pour ce sort !"),
	Im1171("Impossible de lancer ce sort : Vous avez une portée de %1 à %2 et vous visez à %3 !"),
	Im1172("Impossible de lancer ce sort : la cellule visée n'est pas disponible !"),
	Im1173("Impossible de lancer ce sort autrement qu'en ligne droite !"),
	Im1174("Impossible de lancer ce sort : un obstacle gène votre vue !"),
	Im1175("Impossible de lancer ce sort actuellement."),
	Im1176("Votre monture est trop jeune pour être chevauchée. Il faut d'abord l'élever correctement en enclos pour qu'elle grandisse un peu..."),
	Im1177("Vous avez trop d'objets dans votre inventaire, vous ne pouvez pas les voir tous."),
	Im1178("Vous avez trop de montures à l'étable, retirez-en quelque-unes pour les voir toutes."),
	Im1179("Vous avez trop d'objets dans votre banque, retirez-en quelque-uns pour les voir tous."),
	Im118("L'heure actuelle ne convient pas."),
	Im1180("Ce percepteur est en train d'être récolté, vous ne pouvez pas l'attaquer."),
	Im1181("Cette rune est trop puissante pour être ajoutée sur cette arme."),
	Im1182("<b>%1</b> vient d'être déconnecté, il quittera la partie dans <b>%2</b> tour(s), s'il ne se reconnecte pas avant."),
	Im1183("La zone 'Incarnam' fonctionne sur plusieurs instances, pour éviter qu'un trop grand nombre de joueurs soient présent dans cette zone de petite taille. Ceci signifie qu'il existe plusieurs 'Incarnam' en parallèle, afin qu'il n'y ait pas plus d'un certain nombre de joueurs dans la même instance. Vous pouvez donc ne pas être dans le même 'Incarnam' que vos amis, pour les rejoindre, vous pouvez utiliser la liste d'amis, et vous retrouver instantanément à leurs côtés, à conditions qu'ils soient eux aussi dans Incarnam en dehors des grottes et donjons."),
	Im1184("<b>%1</b> vient de se reconnecter en combat."),
	Im1185("Tu ne peux pas t'incarner si tu es mort."),
	Im1186("Comme ton équipe a remporté le combat, ton personnage <b>%1</b> a été sauvé de justesse d'une mort affreuse."),
	Im1187("Une déconnexion massive a été détectée : ton personnage <b>%1</b> est sauvé d'une mort affreuse."),
	Im1188("Une déconnexion massive a été détectée : le combat est annulé."),
	Im1189("Il y a déjà trop de personnes présentes"),
	Im119("Tes caractéristiques ne conviennent pas"),
	Im1190("Ton personnage <b>%1</b> est mort, rien ni personne n'a pu le sauver."),
	Im1191("Tu ne peux plus faire cette quête aujourd'hui, car tu l'as déjà finie avec un autre de tes personnages."),
	Im1192("Ton personnage <b>%1</b> a été sauvé d'une mort affreuse, car le combat n'était pas fini lorsque le serveur s'est éteint."),
	Im1193("Impossible de lancer ce sort : la cellule visée n'est pas valide !"),
	Im1194("Il y a trop de monstres invoqués sur la carte !"),
	Im1195("Vous ne pouvez pas utiliser cet objet sur un personnage qui n'a pas activé son mode \"Joueur contre joueur\"."),
	Im1196("Ton alignement ne te permet pas d'utiliser ce transport !"),
	Im1197("Tu ne peux utiliser cet objet que sur des joueurs d'alignement opposé !"),
	Im1198("Malgré toutes vos tentatives, votre cible reste introuvable. Réessayez plus tard."),
	Im1199("Ton meneur a quitté la guilde <b>%2</b>, et c'est <b>%1</b> qui a été désigné pour le remplacer."),
	Im12("Tu n'exerces pas le métier nécessaire."),
	Im120("Cet emplacement de stockage est déjà utilisé."),
	Im121("Action impossible car ton abonnement a expiré."),
	Im122("Le joueur %1 n'est pas abonné. Action impossible..."),
	Im123("Impossible de devenir marchand : tu n'as aucun objet à vendre..."),
	Im124("Vous ne pouvez devenir vendeur que sur une case vide."),
	Im125("Impossible : il ne peut y avoir plus de %1 vendeurs sur cette carte."),
	Im126("Impossible de se téléporter dans une maison verrouillée."),
	Im127("Action impossible car ta période d'essai est terminée."),
	Im128("<b>En attente du joueur %1...</b>"),
	Im129("<b>En attente des joueurs %1...</b>"),
	Im13("Tu n'as pas le niveau nécessaire."),
	Im130("<b>Perte de la connexion : le joueur %1 a été exclu de la partie</b>"),
	Im131("Cette action nécessite un abonnement valide."),
	Im132("Tu ne peux pas avoir plus de %1 maison(s),."),
	Im133("Impossible d'agresser un joueur de si faible niveau."),
	Im134("Certaines conditions ne sont pas satisfaites."),
	Im135("Etre marié ou ne pas l'être... Tu sembles ne pas avoir fait le bon choix."),
	Im136("Ton épouse n'est pas connectée."),
	Im137("Ton mari n'est pas connecté."),
	Im138("Tu n'es pas marié(e),."),
	Im139("Ton épouse n'est pas disponible pour l'instant..."),
	Im14("Tu ne possèdes pas l'objet nécessaire."),
	Im140("Ton époux n'est pas disponible pour l'instant..."),
	Im141("Il n'y a pas de place disponible près de ton épouse."),
	Im142("Il n'y a pas de place disponible près de ton époux."),
	Im143("Pour utiliser cet objet."),
	Im144("pour équiper cet objet."),
	Im145("pour rentrer ici."),
	Im146("Tu n'exerces pas le métier %1."),
	Im147("Ton niveau est trop faible pour prendre part à une agression."),
	Im148("Vous étiez au mauvais endroit, au mauvais moment, et votre corps à été réduit en charpie."),
	Im149("Impossible de désapprendre le métier <b>%1</b>."),
	Im15("Tu n'appartiens pas à la bonne classe."),
	Im150("Vous aviez oublié votre familier, il a dû trouver à manger tout seul. Mais son état laisse à penser qu'il n'a pas très bien réussi."),
	Im151("Vous aviez oublié votre familier, il est trop gros pour chasser tout seul et à dû se résigner à manger ce qui traînait. Il a perdu du poids mais aussi de sa puissance."),
	Im152("Vous aviez oublié votre familier qui était déjà trop maigre. Il a tenté de manger quelque chose qui traînait mais sans grand succès. Il est maintenant au plus mal."),
	Im153("Votre familier prend la ressource, la renifle un peu, ne semble pas convaincu et vous la rend."),
	Im154("Vous n'avez pas assez fait attention à votre familier. Il s'est transformé en fantôme !"),
	Im155("Le niveau de ta guilde ne te permet pas d'avoir plus de %1 membres."),
	Im156("Il est trop tard"),
	Im157("Impossible de rejoindre ce combat en mode 'Spectateur'."),
	Im158("Vérifie les Emote que tu connais déjà, et réessaye..."),
	Im159("Votre apparence ne vous permet pas d'exécuter cette action."),
	Im16("Impossible d'apprendre le métier %1."),
	Im160("Votre arme vient de se dématérialiser entre votre mains."),
	Im161("Il faut posséder une maison pour utiliser cet objet."),
	Im162("Action impossible avec un compte non abonné. <font color=\"#0000FF\"><u><a href='asfunction:onHref,OpenPayZoneDetails'>Comment devenir membre de la communauté ?</a></u></font>"),
	Im163("Action impossible car votre interlocuteur est trop chargé."),
	Im164("Cet objet ne fait pas partie des catégories prévues dans cet hôtel de vente."),
	Im165("Vous ne disposez pas d'assez de kamas pour acquitter la taxe de mise en vente..."),
	Im166("Vous ne pouvez pas mettre plus d'objets en vente actuellement..."),
	Im167("Vous ne pouvez pas mettre plus d'objets en vente actuellement..."),
	Im168("Cet objet ne peut être accepté ici vu sa rareté..."),
	Im17("Impossible d'apprendre le sort %1."),
	Im170("Action annulée pour cause de surcharge..."),
	Im171("Vous ne disposez pas d'assez de kamas pour acheter cet objet."),
	Im172("Cet objet n'est plus disponible à ce prix. Quelqu'un a été plus rapide..."),
	Im174("Action annulée. Désolé, l'hôtel des ventes est clos temporairement. Revenez un peu plus tard !!"),
	Im175("pour débuter cette quête."),
	Im176("Vous n'avez pas assez de kamas pour acquitter la taxe de mise en mode marchand..."),
	Im177("Cette personne est déjà alignée."),
	Im178("Votre état et celui de votre mari ne vous permet pas de le rejoindre actuellement."),
	Im179("Votre état et celui de votre femme ne vous permet pas de la rejoindre actuellement."),
	Im18("Il faut être au moins niveau %1 dans tous ses métiers pour en apprendre un autre."),
	Im180("Votre mari est trop éloigné pour vous permettre de le rejoindre."),
	Im181("Votre femme est trop éloignée pour vous permettre de la rejoindre."),
	Im182("Vous n'avez pas assez de kamas pour effectuer cette action."),
	Im183("Votre déshonneur ne vous permet pas de faire cette action."),
	Im184("Votre message n'a pas abouti car identique au précédent message."),
	Im185("Vous devez équiper votre outil pour cette action."),
	Im186("Impossible de ressusciter une personne d'une cité ennemie."),
	Im187("L'abonnement lié au cadeau a été invalidé. L'objet est donc repris."),
	Im188("Votre familier ne peut vous suivre tant que vous êtes sur votre monture..."),
	Im189("Bienvenue sur DOFUS, dans le Monde des Douze ! \nRappel : prenez garde, il est interdit de transmettre votre identifiant de connexion ainsi que votre mot de passe."),
	Im189_MINICLIP("Bienvenue sur DOFUS, dans le Monde des Douze ! \nRappel : prenez garde, il est interdit de transmettre votre identifiant de connexion ainsi que votre mot de passe."),
	Im19("Tu connais déjà suffisamment de métiers."),
	Im190("Votre monture semble ne pas vouloir avaler cette nourriture..."),
	Im191("Action impossible en cours de combat."),
	Im192("Impossible de modifier la structure des enclos publics."),
	Im193("Impossible de modifier la structure d'un enclos qui ne vous appartient pas."),
	Im194("Impossible de vendre un enclos public."),
	Im195("Impossible de vendre un enclos qui ne vous appartient pas."),
	Im196("Impossible d'acheter un enclos public."),
	Im197("Impossible d'acheter un enclos non en vente."),
	Im198("Seul le meneur de la guilde peut acheter des enclos."),
	Im199("Prix invalide.");
	
	public final String text;
	
	private Im(String text) {
		this.text = text;
	}
	
	@Override
	public String toString() {
		return this.text;
	}
}